routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    if(Auth::user()){
        if(Auth::user()->role_id == 1){
            return redirect('personal-info');
        }else{
            return redirect('candidates');
        }
    }else{
        return redirect('dashboard');
    }
});

Route::group(['middleware' => ['auth']], function () {
    Route::resources([
        'personal-info' => 'PersonalInfoController',
        'personal-education' => 'EducationController'
    ]);
    Route::get('/candidates', 'PersonalInfoController@candidates')->name('test');
    Route::get('/employees', 'PersonalInfoController@employees')->name('employees');
});

Route::get('/dashboard', function(){
    return view('user-dashboard');
})->name('dashboard');
Route::get('/approve/{id}', 'PersonalInfoController@approve');
Route::get('/reject/{id}', 'PersonalInfoController@reject');
Route::get('/announcement', 'PersonalInfoController@announcement')->name('announcement');


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

resources/views/announcement.blade.php
@extends('main', ['currentMenu' => 'mn-announcement'])
@section('content')
        <div class="app-page-title">
            <div class="page-title-wrapper">
                <div class="page-title-heading">
                    <div>Announcement</div>
                </div>   
            </div>
        </div>            
        <div class="row">
            <div class="col-md-4 col-xl-4">
                <div class="card mb-3 widget-content badge-warning">
                    <div class="widget-content-wrapper text-white">
                        <div class="widget-content-left">
                            <div class="widget-heading">Pending</div>
                            <div class="widget-subheading">Hope for the best and prepare for the worst.</div>
                            <br>
                        </div>
                        <div class="widget-content-right">
                            <div class="widget-numbers text-white"><span>{{$dataTotal->pending}}</span></div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-4 col-xl-4">
                <div class="card mb-3 widget-content bg-grow-early">
                    <div class="widget-content-wrapper text-white">
                        <div class="widget-content-left">
                            <div class="widget-heading">Approved</div>
                            <div class="widget-subheading">Don’t be arrogant, because arrogant kills curiosity and passion.</div>
                        </div>
                        <div class="widget-content-right">
                            <div class="widget-numbers text-white"><span>{{$dataTotal->approved}}</span></div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-4 col-xl-4">
                <div class="card mb-3 widget-content badge-danger">
                    <div class="widget-content-wrapper text-white">
                        <div class="widget-content-left">
                            <div class="widget-heading">Rejected</div>
                            <div class="widget-subheading">Remember one thing, the work we do will be worth it.</div>
                        </div>
                        <div class="widget-content-right">
                            <div class="widget-numbers text-white"><span>{{$dataTotal->rejected}}</span></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
        <div class="row">
            <div class="col-md-12">
                <div class="main-card mb-3 card">
                    <div class="card-header">Candidates</div>
                    <div class="table-responsive">
                        <table class="align-middle mb-0 table table-borderless table-striped table-hover">
                            <thead>
                            <tr>
                                <th class="text-center">ID</th>
                                <th>Name</th>
                                <th class="text-center">Position</th>
                                <th class="text-center">Status</th>
                                @if(Auth::user() && Auth::user()->role_id == 2)
                                    <th class="text-center">Actions</th>
                                @endif
                            </tr>
                            </thead>
                            <tbody>
                                @if($personals)
                                    @foreach($personals as $p)
                                    <tr>
                                        <td class="text-center text-muted">
                                            CAN-{{$p->id}}
                                        </td>
                                        <td>
                                            <div class="widget-content p-0">
                                                <div class="widget-content-wrapper">
                                                    <div class="widget-content-left flex2">
                                                        <div class="widget-heading">
                                                            {{$p->firstname}} {{$p->lastname}}
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </td>
                                        <td class="text-center">{{$p->education->position->description}}</td>
                                        <td class="text-center">
                                            @if($p->status_id == 1)
                                                <div class="badge badge-warning">Pending</div>
                                            @elseif($p->status_id == 2)
                                                <div class="badge badge-success">Approved</div>
                                            @else
                                                <div class="badge badge-danger">Rejected</div>
                                            @endif
                                        </td>
                                        @if(Auth::user() && Auth::user()->role_id == 2)
                                        <td class="text-center">
                                            <button type="button" class="btn btn-primary btn-sm btn-detail-personal" data-personal-id="{{$p->id}}" 
                                            data-toggle="modal" data-target=".detail-personal">Details</button>
                                        </td>
                                        @endif
                                    </tr>
                                    @endforeach
                                @endif
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>

@endsection

resources/views/candidates.blade.php
@extends('main', ['currentMenu' => 'mn-candidates'])
@section('content')
        <div class="app-page-title">
            <div class="page-title-wrapper">
                <div class="page-title-heading">
                    <div>Data candidates</div>
                </div>   
            </div>
        </div>            
        <div class="row">
            <div class="col-md-12 col-xl-12">
                <div class="card mb-3 widget-content bg-midnight-bloom">
                    <div class="widget-content-wrapper text-white">
                        <div class="widget-content-left">
                            <div class="widget-heading">Total Candidates</div>
                            <div class="widget-subheading">People who have dreams of working in your company.</div>
                        </div>
                        <div class="widget-content-right">
                            <div class="widget-numbers text-white"><span>{{count($candidates)}}</span></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
       
        <div class="row">
            <div class="col-md-12">
                <div class="main-card mb-3 card">
                    <div class="card-header">Candidates</div>
                    <div class="table-responsive">
                        <table class="align-middle mb-0 table table-borderless table-striped table-hover">
                            <thead>
                            <tr>
                                <th class="text-center">ID</th>
                                <th>Name</th>
                                <th class="text-center">Study Program</th>
                                <th class="text-center">Desired Position</th>
                                <th class="text-center">Actions</th>
                            </tr>
                            </thead>
                            <tbody>
                                @if($candidates)
                                    @foreach($candidates as $can)
                                    <tr>
                                        <td class="text-center text-muted">{{$can->id}}</td>
                                        <td>
                                            <div class="widget-content p-0">
                                                <div class="widget-content-wrapper">
                                                    <div class="widget-content-left flex2">
                                                        <div class="widget-heading">{{$can->firstname}} {{$can->lastname}}</div>
                                                    </div>
                                                </div>
                                            </div>
                                        </td>
                                        <td class="text-center">{{$can->education->study->description}}</td>
                                        <td class="text-center">{{$can->education->position->description}}</td>
                                        <td class="text-center">
                                            <button type="button" class="btn btn-primary btn-sm btn-detail-personal" data-personal-id="{{$can->id}}" 
                                            data-toggle="modal" data-target=".detail-personal">Details</button>
                                        </td>
                                    </tr>
                                    @endforeach
                                @endif
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>

@endsection

resources/views/main.blade.php
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta http-equiv="Content-Language" content="en">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Recruitment</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, shrink-to-fit=no" />
    <meta name="description" content="This is an example dashboard created using build-in elements and components.">
    <meta name="msapplication-tap-highlight" content="no">
    <link href="{{ asset('main') }}/main.css" rel="stylesheet">
    <link href="//cdnjs.cloudflare.com/ajax/libs/font-awesome/3.2.1/css/font-awesome.min.css" rel="stylesheet" />

</head>
<body>
    <div class="app-container app-theme-white body-tabs-shadow fixed-sidebar fixed-header">
        <div class="app-header header-shadow">
            <div class="app-header__logo">
                <!-- <div class="logo-src"></div> -->
                <h5>PT. PRAS</h5>
                <div class="header__pane ml-auto">
                    <div>
                        <button type="button" class="hamburger close-sidebar-btn hamburger--elastic" data-class="closed-sidebar">
                            <span class="hamburger-box">
                                <span class="hamburger-inner"></span>
                            </span>
                        </button>
                    </div>
                </div>
            </div>
            <div class="app-header__mobile-menu">
                <div>
                    <button type="button" class="hamburger hamburger--elastic mobile-toggle-nav">
                        <span class="hamburger-box">
                            <span class="hamburger-inner"></span>
                        </span>
                    </button>
                </div>
            </div>
            <div class="app-header__menu">
                <span>
                    <button type="button" class="btn-icon btn-icon-only btn btn-primary btn-sm mobile-toggle-header-nav">
                        <span class="btn-icon-wrapper">
                            <i class="fa fa-ellipsis-v fa-w-6"></i>
                        </span>
                    </button>
                </span>
            </div>    
            <div class="app-header__content">
                <div class="app-header-right">
                    <div class="header-btn-lg pr-0">
                        <div class="widget-content p-0">
                            <div class="widget-content-wrapper">
                                <div class="widget-content-left  ml-3 header-user-info">
                                    <div class="widget-heading">
                                        @if(Auth::user())
                                            {{Auth::user()->name}}
                                        @else
                                            {{ __('Login / Register') }}
                                        @endif
                                    </div>
                                </div>
                                <div class="widget-content-left">
                                    <div class="btn-group">
                                        <a data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="p-0 btn">
                                            <i class="fa fa-angle-down ml-2 opacity-8"></i>
                                        </a>
                                        <div tabindex="-1" role="menu" aria-hidden="true" class="dropdown-menu dropdown-menu-right">
                                            @if(Auth::user())
                                                <a ref="{{ route('logout') }}" onclick="event.preventDefault();
                                                                document.getElementById('logout-form').submit();" tabindex="0" class="dropdown-item">
                                                    {{ __('Logout') }}
                                                </a>

                                                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                                    @csrf
                                                </form>
                                            @else
                                                <a href="{{route('login')}}" tabindex="0" class="dropdown-item">Login</a>
                                                <a href="{{route('register')}}" tabindex="0" class="dropdown-item">Register</a>
                                            @endif
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>        
                </div>
            </div>
        </div>        
           
        <div class="app-main">
                <div class="app-sidebar sidebar-shadow">
                    <div class="app-header__logo">
                        <div class="logo-src"></div>
                        <div class="header__pane ml-auto">
                            <div>
                                <button type="button" class="hamburger close-sidebar-btn hamburger--elastic" data-class="closed-sidebar">
                                    <span class="hamburger-box">
                                        <span class="hamburger-inner"></span>
                                    </span>
                                </button>
                            </div>
                        </div>
                    </div>
                    <div class="app-header__mobile-menu">
                        <div>
                            <button type="button" class="hamburger hamburger--elastic mobile-toggle-nav">
                                <span class="hamburger-box">
                                    <span class="hamburger-inner"></span>
                                </span>
                            </button>
                        </div>
                    </div>
                    <div class="app-header__menu">
                        <span>
                            <button type="button" class="btn-icon btn-icon-only btn btn-primary btn-sm mobile-toggle-header-nav">
                                <span class="btn-icon-wrapper">
                                    <i class="fa fa-ellipsis-v fa-w-6"></i>
                                </span>
                            </button>
                        </span>
                    </div>    <div class="scrollbar-sidebar">
                        <div class="app-sidebar__inner">
                            <ul class="vertical-nav-menu">
                                <li class="app-sidebar__heading">Dashboards</li>
                                @if(Auth::user())
                                    @if(Auth::user()->role_id == 1)
                                    <li>
                                        <a id="mn-personal-data" href="{{route('personal-info.index')}}">
                                            <i class="metismenu-icon pe-7s-user"></i>
                                            Personal Data
                                        </a>
                                    </li>
                                    <li>
                                        <a id="mn-education" href="{{route('personal-education.index')}}">
                                            <i class="metismenu-icon pe-7s-study"></i>
                                            Education
                                        </a>
                                    </li>
                                    @endif
                                    @if(Auth::user()->role_id == 2)
                                    <li>
                                        <a id="mn-candidates" href="{{route('test')}}">
                                            <i class="metismenu-icon pe-7s-users"></i>
                                            Candidates
                                        </a>
                                    </li>
                                    <li>
                                        <a id="mn-employees" href="{{route('employees')}}">
                                            <i class="metismenu-icon pe-7s-id"></i>
                                            Employees
                                        </a>
                                    </li>
                                    @endif
                                @else
                                    <li>
                                        <a id="mn-home" href="{{route('dashboard')}}">
                                            <i class="metismenu-icon pe-7s-home"></i>
                                            Home
                                        </a>
                                    </li>
                                @endif
                                
                                <li class="app-sidebar__heading">Other</li>
                                <li>
                                    <a id="mn-announcement" href="{{route('announcement')}}">
                                        <i class="metismenu-icon pe-7s-display2"></i>
                                        Announcement
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div> 
                <div class="app-main__outer">
                    <div class="app-main__inner">
                    @include('flash-message')
                    <br>
                    @yield('content')
                    </div>
                    <div class="app-wrapper-footer">
                        <div class="app-footer">
                            <div class="app-footer__inner">
                                <div class="app-footer-right">
                                    <ul class="nav">
                                        <li class="nav-item">
                                            TMSJ 2019
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>    
                </div>
        </div>
    </div>
    @include('modals')

    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.js"></script>
    <script type="text/javascript" src="{{ asset('main') }}/scripts/main.js"></script>
    <script>
        currentMenu = "<?php echo $currentMenu ?>";
        $(document).ready(function(){
            $("a#"+currentMenu).addClass("mm-active");
            alertSession = $("#alert-session");
            if(alertSession.length != 0){
                alertSession.fadeTo(2000, 500).slideUp(500, function(){
                    alertSession.slideUp(300);
                });
            }

            $('.btn-detail-personal').click(function(){
                personalId = $(this).data('personal-id');
                $.get("/personal-info/"+personalId, function( data ) {
                    $('.set-id').css("display", "none");

                    $('.detail-personal .fullname').text(data.firstname+" "+data.lastname);
                    $('.detail-personal .gender').text(data.gender.description);
                    $('.detail-personal .birthday').text(data.birthday);
                    $('.detail-personal .phone').text(data.phone);
                    $('.detail-personal .address').text(data.address);
                    $('.detail-personal .study-program').text(data.education.study.description);
                    $('.detail-personal .gpa').text(data.education.gpa);
                    $('.detail-personal .position').text(data.education.position.description);
                    $.each(data.skills, function( index, value ) {
                        $('.expertise').append( "<p class='list-group-item-action list-group-item'>"+
                        value.skill.description
                        +"</p>" );
                    });
                    
                    if(currentMenu == "mn-candidates"){
                        $('.set-id').css("display", "block");
                        $('.set-id').data("personal-id", data.id);
                    }
                });
            })

            $('.approve').click(function(){
                if(confirm("Do you seriously want to approve these candidates?")) 
                    document.location = "/approve/"+$(this).data('personal-id');
            })

            $('.reject').click(function(){
                if(confirm("Do you seriously want to reject these candidates?")) 
                    document.location = "/reject/"+$(this).data('personal-id');
            })
        })
    </script>
</body>
</html>

resources/views/personal-data-form.blade.php
@extends('main', ['currentMenu' => 'mn-personal-data'])
@section('content')
<div class="app-page-title">
    <div class="page-title-wrapper">
        <div class="page-title-heading">
            <div>Personal Data
                @if($personalData)
                    <div class="page-title-subheading">
                        Your personal data bellow
                    </div>
                @else
                    <div class="page-title-subheading">
                        Please input all required data
                    </div>
                @endif
            </div>
        </div> 
</div>
</div>            
@if($personalData)
    <div class="main-card mb-3 card">
        <div class="card-body">
            <h5 class="card-title">Personal data</h5>
            <div class="form-row">
                <div class="col-md-6 mb-3">
                    <h6 class="badge badge-primary">First Name</h6>
                    <p>{{$personalData->firstname}}</p>
                </div>
                <div class="col-md-6 mb-3">
                    <h6 class="badge badge-primary">Last Name</h6>
                    <p>{{$personalData->lastname}}</p>
                </div>
            </div>
            <div class="form-row">
                <div class="col-md-6 mb-3">
                    <h6 class="badge badge-primary">Gender</h6>
                    <p>{{$personalData->gender->description}}</p>
                </div>
                <div class="col-md-6 mb-3">
                    <h6 class="badge badge-primary">Date of Birth</h6>
                    <p>{{ date('d M Y' , $personalData->birthday)}}</p>
                </div>
            </div>
            <div class="form-row">
                <div class="col-md-6 mb-3">
                    <h6 class="badge badge-primary">Phone Number</h6>
                    <p>{{$personalData->phone}}</p>
                </div>
                <div class="col-md-6 mb-3">
                    <h6 class="badge badge-primary">Address</h6>
                    <p>{{$personalData->address}}</p>
                </div>
            </div>
        </div>
    </div>
@else
    <div class="main-card mb-3 card">
        <div class="card-body">
            <h5 class="card-title">Personal data form</h5>
            <form action="{{route('personal-info.store')}}" method="post" class="needs-validation" novalidate>
                @csrf
                <div class="form-row">
                    <div class="col-md-6 mb-3">
                        <label class="badge badge-primary" for="input-firstname">First name</label>
                        <input name="firstname" type="text" class="form-control" id="input-firstname" placeholder="First name" required>
                        <div class="valid-feedback">
                            Looks good!
                        </div>
                    </div>
                    <div class="col-md-6 mb-3">
                        <label class="badge badge-primary" for="input-lastname">Last name</label>
                        <input name="lastname" type="text" class="form-control" id="input-lastname" placeholder="Last name" required>
                        <div class="valid-feedback">
                            Looks good!
                        </div>
                    </div>
                </div>
                <div class="form-row">
                    <div class="col-md-6 mb-3">
                        <label class="badge badge-primary" for="select-gender">Gender</label>
                        <select name="gender" id="select-gender" class="form-control">
                            @foreach($gender as $gen)
                                <option value="{{$gen->id}}">{{$gen->description}}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="col-md-6 mb-3">
                        <label class="badge badge-primary" for="input-birthday">Date of Birth</label>
                        <input name="birthday" type="date" class="form-control" id="input-birthday" placeholder="Last name" required>
                        <div class="valid-feedback">
                            Looks good!
                        </div>
                    </div>
                </div>
                <div class="form-row">
                    <div class="col-md-6 mb-3">
                        <label class="badge badge-primary" for="input-phone">Phone Number</label>
                        <input name="phone" type="text" class="form-control" id="input-phone" placeholder="+6282xxxxxx" required>
                        <div class="valid-feedback">
                            Looks good!
                        </div>
                    </div>
                    <div class="col-md-6 mb-3">
                        <label class="badge badge-primary" for="input-address">Address</label>
                        <input name="address" type="text" class="form-control" id="input-address" placeholder="Ir. Soekarno Street, No. 23" required>
                        <div class="invalid-feedback">
                            Please provide a valid address.
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="form-check">
                        <input class="form-check-input" type="checkbox" value="" id="invalidCheck" required>
                        <label class="form-check-label" for="invalidCheck">
                            I have correctly entered the data. 
                        </label>
                        <div class="invalid-feedback">
                            You must agree before submitting.
                        </div>
                    </div>
                </div>
                <button class="btn btn-primary" type="submit">Submit</button>
            </form>

            <script>
                // Example starter JavaScript for disabling form submissions if there are invalid fields
                (function() {
                    'use strict';
                    window.addEventListener('load', function() {
                        // Fetch all the forms we want to apply custom Bootstrap validation styles to
                        var forms = document.getElementsByClassName('needs-validation');
                        // Loop over them and prevent submission
                        var validation = Array.prototype.filter.call(forms, function(form) {
                            form.addEventListener('submit', function(event) {
                                if (form.checkValidity() === false) {
                                    event.preventDefault();
                                    event.stopPropagation();
                                }
                                form.classList.add('was-validated');
                            }, false);
                        });
                    }, false);
                })();
            </script>
        </div>
    </div>
@endif
@endsection